### PR TITLE
fixed #139

### LINKED ISSUE #139: Unable to send transactions
**Describe the bug**
The user is unable to send transactions due to multiple issues in the latest staging branch.

- [x] Amount is invalid even with POKT field filled.
- [x] Decimals like **34,174.74** are throwing an error.

### PR DESCRIPTION
**Pull request by pabelnl**
Closes #139

### CODE REVIEW

**Review by wgarcia4190 — APPROVED** [review]

File: src/views/send/index.js [hunk 1]
```diff
@@ -234,113 +234,39 @@ class Send extends Component {
...
-            }
-        } else {
-            this.toggleAmountError("Amount is invalid.");
-            this.setState({isAmountValid: false});
-            return;
-        }
-    }
+            // Convert the decimals to upokt to use the value for the send-tx
+            // Math.round to remove the decimals
+            const upoktValue = Math.round(amountValue * 1000000);
```
Comment (Evalir) [inline src/views/send/index.js:240]: This might probably overflow, but considering we're soon revamping the wallet, we can probably let this one slip by...

**Review by Evalir — APPROVED** [review]
